# LDA w/ Python Part 1

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [7]:
npr.shape

(11992, 1)

In [6]:
len(npr['Article'][0])

7646

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [12]:
# since it's unsupervised, we have no train/text split

dtm = cv.fit_transform(npr['Article'])

In [13]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [14]:
11992 * 54777, 3033388 / (11992 * 54777)

(656885784, 0.004617831705123337)

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [19]:
import time

In [24]:
start = time.time()


In [25]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [26]:
end = time.time()

In [27]:
print(f'Minutes Elapsed: {(end-start)/60:.2f}')

Minutes Elapsed: 1.10


# LDA w/ Python Part 2

In [28]:
# Grab the Vocabulary of Words

In [31]:
len(cv.get_feature_names()),type(cv.get_feature_names()), dtm.shape

(54777, list, (11992, 54777))

In [34]:
cv.get_feature_names()[50000]

'transcribe'

In [40]:
import random

random_word_id = random.randint(0,dtm.shape[1])

cv.get_feature_names()[random_word_id]

'sliver'

In [ ]:
# Grab the Topics

In [44]:
LDA.components_.shape, type(LDA.components_)

((7, 54777), numpy.ndarray)

In [45]:
single_topic = LDA.components_[0]

In [ ]:
single_topic.argsort()

In [46]:
import numpy as np

In [59]:
arr = np.random.randint(0,1000,5)
arr

array([677, 424, 655, 748, 634])

In [60]:
arr.argsort()

array([1, 4, 2, 0, 3])

In [61]:
# Argsort returns index positions from LEAST to GREATEST

single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [66]:
n= 20
top_n_words = single_topic.argsort()[-20:]

In [67]:
for idx in top_n_words:
    print(cv.get_feature_names()[idx])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [ ]:
# Grab the Highest probability words  per topic

In [69]:
m = 15
print(f'TOP {m} words for each topic\n\n')
for idx, topic in enumerate(LDA.components_):
    print(f'TOPIC # {idx}:')
    print([cv.get_feature_names()[index] for index in topic.argsort()[-m:]])
    print('\n\n')

TOP 15 words for each topic


TOPIC # 0:
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']



TOPIC # 1:
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']



TOPIC # 2:
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']



TOPIC # 3:
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']



TOPIC # 4:
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']



TOPIC # 5:
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']



TOPIC # 6:
['student', 'years', 'data', 'science'

In [70]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [71]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [72]:
topic_results = LDA.transform(dtm)

In [73]:
topic_results.shape

(11992, 7)

In [77]:
topic_results[0].round(2), topic_results[0].argmax()

(array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ]), 1)

In [ ]:
topic_results.

In [78]:
npr['topic'] = topic_results.argmax(axis=1)

In [80]:
npr.head(20)

Article  topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      2
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1